# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shirt_size',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
