# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170504_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Team'),
        ),
    ]
