# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170508_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge'), ('XXL', 'XXLarge')], max_length=25),
        ),
    ]
