# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20170508_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Season'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
