# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170509_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
