# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_season_registration_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
