# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_season_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
