# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_player_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='credit',
            field=models.BooleanField(default=False),
        ),
    ]
